In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt         
import seaborn as sns  
import os

In [14]:
pwd

'C:\\Users\\eya\\desktop\\coursera python\\u'

In [35]:
df=pd.read_csv(r"C:\Users\eya\desktop\coursera python\final_project_duke\all_data.csv")
df.head(41)

,Ws Property Id,profitable properties,Apt House,City,group,Kitchen,Location,"Net Change in Profits, each year thereafter (for next 4 years) (bin)",number_bedrooms,Property Type,...,Num Bedrooms,Optimal Rent,Percentile 10Th Price,Percentile 90Th Price,profitable (fixed),profitable (variable),ST example $ Rent,ST occupancy rate,Variable Costs - Conversion Year and After,Variable Costs - Conversion Year and After fixe
0,W103,profitable,house,Austin,W103,Y,L15257,7K,1 BD,R10,...,1,371.508150,202,646,1,1,380,0.410959,6445.298243,6445.298243
1,W107,profitable,house,Austin,W107,Y,L15260,52K,1 BD,R10,...,1,845.729088,239,1431,1,1,969,0.109589,5465.282998,5465.282998
2,W108,profitable,house,Austin,W108,Y,L15260,37K,2 BD,R14,...,2,908.200610,236,1533,1,1,885,0.224658,5393.857339,5393.857339
3,W109,profitable,apartment,Austin,W109,Y,L15264,0K,1 BD,R2,...,1,320.012067,138,550,1,1,287,0.219178,5983.107168,5983.107168
4,W110,profitable,apartment,Austin,W110,Y,L15264,22K,2 BD,R6,...,2,539.565422,175,917,1,1,462,0.536986,5601.416258,5601.416258
5,W111,profitable,house,Austin,W111,Y,L15264,15K,1 BD,R10,...,1,485.993540,130,821,1,1,389,0.512329,5417.639361,5417.639361
6,W112,profitable,house,Austin,W112,Y,L15264,22K,2 BD,R14,...,2,501.282869,241,866,1,1,678,0.361644,6178.179021,6178.179021
7,W114,profitable,apartment,Austin,W114,Y,L15278,22K,2 BD,R6,...,2,458.181451,234,794,1,1,374,0.915068,6302.416762,6302.416762
8,W115,profitable,house,Austin,W115,Y,L15278,15K,1 BD,R10,...,1,305.729514,252,547,1,1,444,0.430137,7983.126164,7983.126164
9,W116,profitable,house,Austin,W116,Y,L15278,15K,2 BD,R14,...,2,348.423458,246,616,1,1,426,0.482192,7253.762063,7253.762063
10,W118,profitable,apartment,Austin,W118,Y,L15280,7K,2 BD,R6,...,2,316.822040,262,567,1,1,430,0.523288,8001.532792,8001.532792
11,W119,profitable,house,Austin,W119,Y,L15280,22K,1 BD,R10,...,1,498.329132,229,859,1,1,662,0.449315,6093.030746,6093.030746
12,W120,profitable,house,Austin,W120,Y,L15280,45K,2 BD,R14,...,2,498.663666,449,899,1,1,696,0.487671,8535.969489,8535.969489
13,W123,profitable,house,Bentonville,W123,Y,L463,7K,1 BD,R10,...,1,206.198920,215,377,1,1,363,0.139726,9386.096667,9386.096667
14,W130,profitable,apartment,Denver,W130,Y,L2314,0K,2 BD,R6,...,2,253.518843,228,457,1,1,377,0.479452,8527.709643,8527.709643
15,W143,profitable,house,Denver,W143,Y,L2325,7K,1 BD,R10,...,1,269.191085,263,489,1,1,429,0.210959,9175.080369,9175.080369
16,W144,profitable,house,Denver,W144,Y,L2325,15K,2 BD,R14,...,2,269.245183,335,502,1,1,441,0.331507,9386.096667,9386.096667
17,W152,profitable,house,Miami,W152,Y,L3244,30K,2 BD,R14,...,2,428.780752,386,773,1,1,536,0.542466,8534.576189,8534.576189
18,W155,profitable,house,Miami,W155,Y,L3256,97K,1 BD,R10,...,1,1247.544352,448,2128,1,1,1477,0.693151,5720.109667,5720.109667
19,W156,profitable,house,Miami,W156,Y,L3256,120K,2 BD,R14,...,2,1595.209076,450,2699,1,1,1265,0.715068,5463.686839,5463.686839
20,W157,profitable,apartment,Miami,W157,Y,L3261,15K,1 BD,R2,...,1,203.988249,291,387,1,1,328,0.520548,9386.096667,9386.096667
21,W159,profitable,house,Miami,W159,Y,L3261,15K,1 BD,R10,...,1,209.299280,287,395,1,1,325,0.545205,9386.096667,9386.096667
22,W160,profitable,house,Miami,W160,Y,L3261,22K,2 BD,R14,...,2,264.765826,376,502,1,1,428,0.586301,9386.096667,9386.096667
23,W163,profitable,house,Miami,W163,Y,L3262,60K,1 BD,R10,...,1,687.145138,486,1215,1,1,860,0.410959,7260.701667,7260.701667
24,W164,profitable,house,Miami,W164,Y,L3262,75K,2 BD,R14,...,2,948.892437,516,1650,1,1,729,0.682192,6445.573624,6445.573624
25,W168,profitable,house,Miami,W168,Y,L3264,7K,2 BD,R14,...,2,229.623120,285,428,1,1,342,0.391781,9386.096667,9386.096667
26,W179,profitable,house,Omaha,W179,Y,L10133,7K,1 BD,R10,...,1,262.981473,186,465,1,1,325,0.454795,7260.701667,7260.701667
27,W188,profitable,house,San Diego,W188,Y,L1882,15K,2 BD,R14,...,2,499.766142,227,861,1,1,568,0.189041,6072.048270,6072.048270
28,W190,profitable,apartment,San Diego,W190,Y,L1883,37K,2 BD,R6,...,2,604.776093,225,1033,1,1,538,0.580822,5765.552046,5765.552046
29,W192,profitable,house,San Diego,W192,Y,L1883,22K,2 BD,R14,...,2,512.156890,253,886,1,1,680,0.386301,6232.423436,6232.423436
30,W194,profitable,apartment,San Diego,W194,Y,L1887,0K,2 BD,R6,...,2,464.136246,107,781,1,1,579,0.410959,5304.485069,5304.485069
31,W196,profitable,house,San Diego,W196,Y,L1887,7K,2 BD,R14,...,2,534.720938,158,906,1,1,560,0.276712,5506.596248,5506.596248
32,W198,profitable,apartment,San Diego,W198,Y,L1902,15K,2 BD,R6,...,2,321.909591,366,594,1,1,417,0.531507,9386.096667,9386.096667
33,W199,profitable,house,San Diego,W199,Y,L1902,7K,1 BD,R10,...,1,368.771860,333,665,1,1,474,0.427397,8556.129177,8556.129177
34,W28,profitable,house,Chicago,W28,Y,L4770,7K,2 BD,R14,...,2,440.866502,175,755,1,1,487,0.430137,5855.132816,5855.132816
35,W46,profitable,house,New York,W46,Y,L11431,22K,1 BD,R10,...,1,771.564680,165,1296,1,1,420,0.871233,5254.935336,5254.935336
36,W47,profitable,house,New York,W47,Y,L11431,7K,2 BD,R14,...,2,599.468979,268,1032,1,1,593,0.506849,6044.091056,6044.091056
37,W50,profitable,house,New York,W50,Y,L11434,7K,1 BD,R10,...,1,619.092099,133,1040,1,1,621,0.347945,5257.818829,5257.818829
38,W54,profitable,house,New York,W54,Y,L11480,0K,1 BD,R10,...,1,516.704211,111,868,1,1,471,0.600000,5257.796391,5257.796391
39,W66,profitable,house,Palo Alto,W66,Y,L1735,30K,1 BD,R10,...,1,737.349033,283,1261,1,1,980,0.271233,5807.535900,5807.535900
40,W67,profitable,house,Palo Alto,W67,Y,L1735,37K,2 BD,R14,...,2,767.024134,530,1354,1,1,994,0.430137,7170.335227,7170.335227

In [34]:
df.shape

(41, 61)

In [36]:
df.head(0)

Empty DataFrame
Columns: [Ws Property Id, profitable properties, Apt House, City, group, Kitchen, Location, Net Change in Profits, each year thereafter (for next 4 years)  (bin), number_bedrooms, Property Type, Shared, State, Zipcode, $ 90th-$10th, Change in Gross Rental Revenue, Change in Gross Rental Revenue fixe, Correct Forecast Occupancy Rate , Correct Nightly $ Rent, Correct Nightly Rent Normalized to Percentile, Current Monthly Rent, Forecast ST annual Revenues After Transaction Fees, Forecast ST annual Revenues After Transaction Fees fixe, Forecast ST annual Revenues Before Transaction Fees, Interm Result1, Interm Result2, Interm Result3, LT Annual Revenues, model dynamic net change in cash flow conversion year , model dynamic net change in cash flow year thereafter , model dynamic net profits conversion year, model dynamic net profits each year, model fixed net change in cash flow conversion year , model fixed net change in cash flow year thereafter  , model fixed net profits conversion year , model fixed net profits each year, Net Change in Cash Flow, Each Year Thereafter (for next 4 years) , Net Change in Cash Flow, Each Year Thereafter (for next 4 years)  fixe, Net Change in Profits, Conversion year, Net Change in Profits, Conversion year fixe, Net Change in Profits, each year thereafter (for next 4 years) , Net Change in Profits, each year thereafter (for next 4 years)  fixe, Net Forecast Change in Cash Flow, Conversion Year , Net Forecast Change in Cash Flow, Conversion Year  fixe, New Cash Out - each year thereafter, New Cash Out - each year thereafter fixe, New Cash Out,  Conversion year , New Cash Out,  Conversion year  fixe, New Change in Profits, Conversion Year, New Change in Profits, Conversion Year fixe, New Change in Profits, Each Year Thereafter, New Change in Profits, Each Year Thereafter fixe, Num Bedrooms, Optimal Rent, Percentile 10Th Price, Percentile 90Th Price, profitable (fixed), profitable (variable) , ST example $ Rent, ST occupancy rate , Variable Costs - Conversion Year and After, Variable Costs - Conversion Year and After fixe]
Index: []

[0 rows x 61 columns]

In [38]:
df.columns

Index(['Ws Property Id', 'profitable properties', 'Apt House', 'City', 'group',
       'Kitchen', 'Location',
       'Net Change in Profits, each year thereafter (for next 4 years)  (bin)',
       'number_bedrooms', 'Property Type', 'Shared', 'State', 'Zipcode',
       '$ 90th-$10th', 'Change in Gross Rental Revenue',
       'Change in Gross Rental Revenue fixe',
       'Correct Forecast Occupancy Rate ', 'Correct Nightly $ Rent',
       'Correct Nightly Rent Normalized to Percentile', 'Current Monthly Rent',
       'Forecast ST annual Revenues After Transaction Fees',
       'Forecast ST annual Revenues After Transaction Fees fixe',
       'Forecast ST annual Revenues Before Transaction Fees', 'Interm Result1',
       'Interm Result2', 'Interm Result3', 'LT Annual Revenues',
       'model dynamic net change in cash flow conversion year ',
       'model dynamic net change in cash flow year thereafter ',
       'model dynamic net profits conversion year',
       'model dynamic net profits each year',
       'model fixed net change in cash flow conversion year ',
       'model fixed net change in cash flow year thereafter  ',
       'model fixed net profits conversion year ',
       'model fixed net profits each year',
       'Net Change in Cash Flow, Each Year Thereafter (for next 4 years) ',
       'Net Change in Cash Flow, Each Year Thereafter (for next 4 years)  fixe',
       'Net Change in Profits, Conversion year',
       'Net Change in Profits, Conversion year fixe',
       'Net Change in Profits, each year thereafter (for next 4 years) ',
       'Net Change in Profits, each year thereafter (for next 4 years)  fixe',
       'Net Forecast Change in Cash Flow, Conversion Year ',
       'Net Forecast Change in Cash Flow, Conversion Year  fixe',
       'New Cash Out - each year thereafter',
       'New Cash Out - each year thereafter fixe',
       'New Cash Out,  Conversion year ',
       'New Cash Out,  Conversion year  fixe',
       'New Change in Profits, Conversion Year',
       'New Change in Profits, Conversion Year fixe',
       'New Change in Profits, Each Year Thereafter',
       'New Change in Profits, Each Year Thereafter fixe', 'Num Bedrooms',
       'Optimal Rent', 'Percentile 10Th Price', 'Percentile 90Th Price',
       'profitable (fixed)', 'profitable (variable) ', 'ST example $ Rent',
       'ST occupancy rate ', 'Variable Costs - Conversion Year and After',
       'Variable Costs - Conversion Year and After fixe'],
      dtype='object')

In [42]:
extract=df.loc[:,['Ws Property Id', 'Property Type','Location', 'group','City','State', 'Zipcode','Apt House','number_bedrooms',
       'Net Forecast Change in Cash Flow, Conversion Year ',
        'Net Change in Profits, Conversion year','Net Change in Profits, each year thereafter (for next 4 years) ',
                 'Net Change in Cash Flow, Each Year Thereafter (for next 4 years) ']]
extract.head()

,Ws Property Id,Property Type,Location,group,City,State,Zipcode,Apt House,number_bedrooms,"Net Forecast Change in Cash Flow, Conversion Year","Net Change in Profits, Conversion year","Net Change in Profits, each year thereafter (for next 4 years)","Net Change in Cash Flow, Each Year Thereafter (for next 4 years)"
0,W103,R10,L15257,W103,Austin,TX,78702,house,1 BD,-8442.800870,15557.199130,9557.199130,15557.199130
1,W107,R10,L15260,W107,Austin,TX,78705,house,1 BD,36983.041880,60983.041880,54983.041880,60983.041880
2,W108,R14,L15260,W108,Austin,TX,78705,house,2 BD,26515.737656,50515.737656,44515.737656,50515.737656
3,W109,R2,L15264,W109,Austin,TX,78723,apartment,1 BD,-11051.110808,12948.889192,6948.889192,12948.889192
4,W110,R6,L15264,W110,Austin,TX,78723,apartment,2 BD,9088.724813,33088.724813,27088.724813,33088.724813

In [55]:
extract_final=extract.rename(columns={"Ws Property Id":"Property ID","number_bedrooms":"Number Bedrooms",
                                      "Net Forecast Change in Cash Flow, Conversion Year ":"N.C Cash Flow,Conersion Year",
                        "Net Change in Profits, Conversion year":"N.C in Profits,Conversion Year",
                      "Net Change in Profits, each year thereafter (for next 4 years) ":"N.C in Profits Year thereafter",
                       "Net Change in Cash Flow, Each Year Thereafter (for next 4 years) ":"N.C Cash Flow,Year thereafter"})
extract_final.head(41)

,Property ID,Property Type,Location,group,City,State,Zipcode,Apt House,Number Bedrooms,"N.C Cash Flow,Conersion Year","N.C in Profits,Conversion Year",N.C in Profits Year thereafter,"N.C Cash Flow,Year thereafter"
0,W103,R10,L15257,W103,Austin,TX,78702,house,1 BD,-8442.800870,15557.199130,9557.199130,15557.199130
1,W107,R10,L15260,W107,Austin,TX,78705,house,1 BD,36983.041880,60983.041880,54983.041880,60983.041880
2,W108,R14,L15260,W108,Austin,TX,78705,house,2 BD,26515.737656,50515.737656,44515.737656,50515.737656
3,W109,R2,L15264,W109,Austin,TX,78723,apartment,1 BD,-11051.110808,12948.889192,6948.889192,12948.889192
4,W110,R6,L15264,W110,Austin,TX,78723,apartment,2 BD,9088.724813,33088.724813,27088.724813,33088.724813
5,W111,R10,L15264,W111,Austin,TX,78723,house,1 BD,2262.852991,26262.852991,20262.852991,26262.852991
6,W112,R14,L15264,W112,Austin,TX,78723,house,2 BD,6577.542380,30577.542380,24577.542380,30577.542380
7,W114,R6,L15278,W114,Austin,TX,78744,apartment,2 BD,6727.042777,30727.042777,24727.042777,30727.042777
8,W115,R10,L15278,W115,Austin,TX,78744,house,1 BD,-837.303211,23162.696789,17162.696789,23162.696789
9,W116,R14,L15278,W116,Austin,TX,78744,house,2 BD,-622.363906,23377.636094,17377.636094,23377.636094
10,W118,R6,L15280,W118,Austin,TX,78746,apartment,2 BD,-4711.631993,19288.368007,13288.368007,19288.368007
11,W119,R10,L15280,W119,Austin,TX,78746,house,1 BD,6555.998425,30555.998425,24555.998425,30555.998425
12,W120,R14,L15280,W120,Austin,TX,78746,house,2 BD,28570.565051,52570.565051,46570.565051,52570.565051
13,W123,R10,L463,W123,Bentonville,AR,72712,house,1 BD,-8781.070217,15218.929783,9218.929783,15218.929783
14,W130,R6,L2314,W130,Denver,CO,80204,apartment,2 BD,-11905.872883,12094.127117,6094.127117,12094.127117
15,W143,R10,L2325,W143,Denver,CO,80220,house,1 BD,-6087.033660,17912.966340,11912.966340,17912.966340
16,W144,R14,L2325,W144,Denver,CO,80220,house,2 BD,860.693383,24860.693383,18860.693383,24860.693383
17,W152,R14,L3244,W152,Miami,FL,33122,house,2 BD,12529.725814,36529.725814,30529.725814,36529.725814
18,W155,R10,L3256,W155,Miami,FL,33137,house,1 BD,86018.190964,110018.190964,104018.190964,110018.190964
19,W156,R14,L3256,W156,Miami,FL,33137,house,2 BD,106603.292650,130603.292650,124603.292650,130603.292650
20,W157,R2,L3261,W157,Miami,FL,33146,apartment,1 BD,-806.459937,23193.540063,17193.540063,23193.540063
21,W159,R10,L3261,W159,Miami,FL,33146,house,1 BD,-2762.492057,21237.507943,15237.507943,21237.507943
22,W160,R14,L3261,W160,Miami,FL,33146,house,2 BD,8942.122613,32942.122613,26942.122613,32942.122613
23,W163,R10,L3262,W163,Miami,FL,33149,house,1 BD,46397.571212,70397.571212,64397.571212,70397.571212
24,W164,R14,L3262,W164,Miami,FL,33149,house,2 BD,60371.303786,84371.303786,78371.303786,84371.303786
25,W168,R14,L3264,W168,Miami,FL,33178,house,2 BD,-10162.308117,13837.691883,7837.691883,13837.691883
26,W179,R10,L10133,W179,Omaha,NE,68110,house,1 BD,-10103.471306,13896.528694,7896.528694,13896.528694
27,W188,R14,L1882,W188,San Diego,CA,91910,house,2 BD,1870.238665,25870.238665,19870.238665,25870.238665
28,W190,R6,L1883,W190,San Diego,CA,91950,apartment,2 BD,21015.076804,45015.076804,39015.076804,45015.076804
29,W192,R14,L1883,W192,San Diego,CA,91950,house,2 BD,8517.527211,32517.527211,26517.527211,32517.527211
30,W194,R6,L1887,W194,San Diego,CA,92102,apartment,2 BD,-10554.405554,13445.594446,7445.594446,13445.594446
31,W196,R14,L1887,W196,San Diego,CA,92102,house,2 BD,-6462.257770,17537.742230,11537.742230,17537.742230
32,W198,R6,L1902,W198,San Diego,CA,92118,apartment,2 BD,-1202.157687,22797.842313,16797.842313,22797.842313
33,W199,R10,L1902,W199,San Diego,CA,92118,house,1 BD,-5085.676089,18914.323911,12914.323911,18914.323911
34,W28,R14,L4770,W28,Chicago,IL,60616,house,2 BD,-9766.762376,14233.237624,8233.237624,14233.237624
35,W46,R10,L11431,W46,New York,NY,10019,house,1 BD,8926.837148,32926.837148,26926.837148,32926.837148
36,W47,R14,L11431,W47,New York,NY,10019,house,2 BD,-4421.944074,19578.055926,13578.055926,19578.055926
37,W50,R10,L11434,W50,New York,NY,10023,house,1 BD,-5529.262779,18470.737221,12470.737221,18470.737221
38,W54,R10,L11480,W54,New York,NY,11101,house,1 BD,-10996.560146,13003.439854,7003.439854,13003.439854
39,W66,R10,L1735,W66,Palo Alto,CA,94301,house,1 BD,11987.464720,35987.464720,29987.464720,35987.464720
40,W67,R14,L1735,W67,Palo Alto,CA,94301,house,2 BD,22183.888361,46183.888361,40183.888361,46183.888361